ACTION_MAILER_DEFAULT_FROM: 'noreply@hireables.com'

development:
  APPLICATION_HOST: 'localhost'
  APPLICATION_PORT: '3000'

  HEROKU_RELEASE_VERSION: 'v1'
  HEROKU_RELEASE_CREATED_AT: '2019-01-01T08:00:00Z'
  HEROKU_SLUG_COMMIT: '70d5b4aecaa7f8e7c151a820bbf9d22cbc46d654'

  RACK_TIMEOUT_SERVICE_TIMEOUT: '0'
  RACK_TIMEOUT_WAIT_TIMEOUT: '0'
  RACK_TIMEOUT_WAIT_OVERTIME: '0'
  RACK_TIMEOUT_SERVICE_PAST_WAIT: 'false'

test:
  APPLICATION_HOST: 'localhost'
  APPLICATION_PORT: '3000'

  HEROKU_RELEASE_VERSION: 'v1'
  HEROKU_RELEASE_CREATED_AT: '2019-01-01T08:00:00Z'
  HEROKU_SLUG_COMMIT: '70d5b4aecaa7f8e7c151a820bbf9d22cbc46d654'

  RACK_TIMEOUT_SERVICE_TIMEOUT: '0'
  RACK_TIMEOUT_WAIT_TIMEOUT: '0'
  RACK_TIMEOUT_WAIT_OVERTIME: '0'
  RACK_TIMEOUT_SERVICE_PAST_WAIT: 'false'
