default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", 'localhost') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: hireables_development

test:
  <<: *default
  database: hireables_test

production:
  url: <%= ENV['DATABASE_URL'] %>
